server:
  port: 8090
  servlet:
    context-path: /


spring:
  application:
    name: elastic

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/prac?serverTimezone=Asia/Seoul
    username: root
    password: db user password

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:config/logback-spring.xml

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*.xml

# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-login-endpoint: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**